name: Setup Dictum
inputs:
  python-version:
    required: true
    default: 3.9
    description: Python version
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ INPUT_PYTHON_VERSION }}
    - run: pip install poetry
      shell: bash
      working_directory: dictum
    - run: poetry install
      shell: bash
      working_directory: dictum
