name: Chinook Example
description: |
  An example project based on Chinook sqlite database. Use for testing, introductory
  tutorial and as a basic example of what can be done here.

unions:
  country:
    name: Country
    type: str

metrics:
  revenue:
    name: Revenue
    table: invoice_items
    expr: sum(UnitPrice * Quantity)
    missing: 0
    type: float
    format: currency
  revenue_per_track:
    name: Revenue per Track in the Library
    expr: $revenue / $track_count
    format: currency

dimensions:
  genre:
    name: Genre
    table: genres
    expr: Name
    type: str
  artist:
    name: Artist
    table: artists
    expr: Name
    type: str
  album:
    name: Album
    table: albums
    expr: Title
    type: str
  media_type:
    name: Media Type
    table: media_types
    expr: Name
    type: str

tables:
  genres:
    source: genres
    primary_key: GenreId
  artists:
    source: artists
    primary_key: ArtistId
  albums:
    source: albums
    primary_key: AlbumId
    related:
      artist:
        table: artists
        foreign_key: ArtistId
  media_types:
    source: media_types
    primary_key: MediaTypeId
