name: Dictum Tutorial

metrics:
  arpu:
    name: Average Revenue per Active User (ARPU)
    expr: $revenue / $unique_active_users
    type: currency
    currency: USD
  ppu:
    name: Percentage of Paying Users
    description: Percentage of active users who made at least one order
    expr: $unique_paying_users / $unique_active_users
    type: percent

unions:
  date:
    name: Date
    description: Event Date. For signups, orders, sessions etc.
    type: datetime
  channel:
    name: Marketing Channel
    type: string

tables:
  categories:
    source: categories
    primary_key: id

  orders:
    source: orders
    primary_key: id
    related:
      category:
        table: categories
        foreign_key: category_id
      user:
        table: users
        foreign_key: user_id
    measures:
      orders:
        name: Number of Orders
        expr: count()
      revenue:
        name: Revenue
        expr: sum(amount)
        type: currency
        currency: USD
      unique_paying_users:
        name: Unique Paying Users
        description: Number of Users Who Made an Order
        expr: countd(user_id)
      arppu:
        name: Average Revenue per Paying Users
        expr: $revenue / $unique_paying_users
        type: currency
        currency: USD
      min_order_date:
        metric: false
        name: min_order_date
        type: datetime
        expr: min(created_at)
    dimensions:
      order_created_at:
        name: Order Date
        type: datetime
        expr: created_at
        union: date
      category:
        name: Order Category
        expr: category.name
        type: string
      order_channel:
        name: Order Channel
        type: string
        expr: channel
        union: channel
      order_day_diff:
        name: Days Since User's First Order
        type: number
        expr: datediff('day', :user_first_order_date, :order_created_at)
      order_month_diff:
        name: Months Since User's First Order
        type: number
        expr: datediff('month', :user_first_order_date, :order_created_at)

  users:
    source: users
    primary_key: id
    measures:
      users:
        name: Number of Users
        expr: count()
      signups:
        name: Number of User Signups
        expr: count()
    dimensions:
      user_created_at:
        name: User Signup Date
        type: datetime
        expr: created_at
        union: date
      user_channel:
        name: User's Marketing Channel
        description: Marketing channel that the user's signup was attributed to
        expr: channel
        type: string
        union: channel
      user_orders_amount:
        name: Users' Total Orders Amount
        type: number
        missing: 0
        expr: $revenue
      user_first_order_date:
        name: User's First Order Date
        expr: $min_order_date
        type: datetime

  sessions:
    source: user_sessions
    primary_key: id
    related:
      user:
        table: users
        foreign_key: user_id
    measures:
      sessions:
        name: Number of Sessions
        expr: count()
      unique_active_users:
        name: Unique Active Users
        expr: countd(user_id)
