site_name: Dictum
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/rad-data-labs/dictum
repo_name: Source code
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
nav:
  - Introduction: index.md
  - Data Model Guide:
    - Getting Started: data_model/getting_started.md
    - Query Intro: data_model/query_intro.md
    - Tables and Measures: data_model/tables.md
    - Dimensions: data_model/dimensions.md
    - Table Relationships: data_model/table_relationships.md
    - Reusable Expressions: data_model/reusable_expressions.md
    - Union Dimensions: data_model/union_dimensions.md
    - Metrics and Measures: data_model/metrics_and_measures.md
    - Aggregate Dimensions: data_model/aggregate_dimensions.md
    - Types and Formatting: data_model/types_formatting.md
    - Organizing a Larger Project with Multiple Files: data_model/multiple_files.md
    - Default Transforms and Filters: data_model/dimension_transforms.md
    # - Table Calculations -: index.md
  # - Query Guide:
  #   - Introduction: query/intro.md
  #   - GraphQL API: index.md
  #   - REST API: index.md
  #   - Querying from Python: index.md
  # - Recipes:
  #   - Cohort Analysis: index.md
  #   - Retention: index.md
  # - Live Demos:
  #   - Tutorial Example: index.md
  #   - Chinook Database: index.md
  #   - AdventureWorks Data Warehouse: index.md
  - Reference:
    - Expression Language: reference/expression_language.md
    - Query Language: reference/query_language.md
    - Python API: reference/python_api.md
    - Backends: reference/backends.md
