site_name: Hyperplane
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/rad-data-labs/hyperplane
repo_name: rad-data-labs/hyperplane
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
nav:
  - Introduction: index.md
  - Data Model Guide:
    - Gettings started: data_model/getting_started.md
    - Tables and Measures: data_model/tables.md
    - Dimensions: data_model/dimensions.md
    - Table Relationships: data_model/table_relationships.md
    - Reusable Expressions: data_model/reusable_expressions.md
    - Union Dimensions: data_model/union_dimensions.md
    - Metrics and Measures: data_model/metrics_and_measures.md
    - Aggregate Dimensions: data_model/aggregate_dimensions.md
    - Dimension Transforms -: index.md
  - Recipes:
    - Cohort Analysis: index.md
    - Retention: index.md
  - Live Demos:
    - Tutorial Example: index.md
    - Chinook Database: index.md
    - AdventureWorks Data Warehouse: index.md
  - Reference:
    - Expression Language: reference/expression_language.md
    - reference/python_api.md
    - Backends:
      - reference/backends.md
      - reference/plugins.md
