name: Test an officially supported backend
inputs:
  backend:
    required: true
    description: Backend type to test
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-dictum
    - uses: oprypin/find-latest-tag@v1
      id: find_tag
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
    - uses: actions/checkout@v3
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
        ref: ${{ steps.find_tag.outputs.tag }}
        path: ${{ inputs.backend }}
    - run: poetry build
      working-directory: ${{ inputs.backend }}
      shell: bash
    - run: pip install ../${{ inputs.backend }}/dist/*.whl
      working-directory: dictum
    - run: poetry run pytest ../${{ inputs.backend }}/tests/
      working-directory: dictum
