name: Test an officially supported backend
inputs:
  backend:
    required: true
    description: Backend type to test
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-dictum
    - uses: oprypin/find-latest-tag@v1
      id: find_tag
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
    - uses: actions/checkout@v3
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
        ref: ${{ steps.find_tag.outputs.tag }}
        path: plugin
    - run: poetry run pip install -e ../dictum-backend-${{ inputs.backend }}/dictum_backend_${{ inputs.backend }}
      working-directory: dictum
      shell: bash
    - run: poetry run pytest -k 'backend and end_to_end'
      working-directory: dictum
      shell: bash
