name: Build and publish the docs to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dictum
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install poetry
      - run: poetry install -n
      - run: poetry run mkdocs build --config-file=../docs/mkdocs.yml
